include $(CLEAR_VARS)

TARGET_MODULE := Processor

CPP_INCLUDE		:= -I$(ROOT_PATH) \
				   -I$(ROOT_PATH)/listener \
				   -I.
CPP_SRCDIR		:= $(shell pwd)
CPP_SRC			:= $(shell find $(CPP_SRCDIR) -name "*.cpp")

LIBS			+=
LIBS_DIR		+=

include $(BUILD_OBJ)
